name: pull-request-security

on:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  dependencies-analysis:
    name: add dependencies
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: run osv-scanner after PR
        uses: google/osv-scanner-action/osv-scanner-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9
        continue-on-error: true
        with:
          scan-args: |-
            --format=json
            --output=dependencies-new.json
            ./

      - name: checkout baseline commit
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}

      - name: run osv-scanner before PR
        uses: google/osv-scanner-action/osv-scanner-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9
        continue-on-error: true
        with:
          scan-args: |-
            --format=json
            --output=dependencies-old.json
            ./

      - name: compare dependency analysis
        uses: google/osv-scanner-action/osv-reporter-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9
        with:
          scan-args: |-
            --output=DependenciesAnalysisDiff.sarif
            --old=dependencies-old.json
            --new=dependencies-new.json
            --gh-annotations=true
            --fail-on-vuln=true

      - name: upload dependency differential report
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: dependencies-analysis-diff
          path: DependenciesAnalysisDiff.sarif
          if-no-files-found: error
          retention-days: 5

  source-code-analysis:
    name: add source code analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:0a014c440663e466a79401c24e0cc8c63e18975cd9eb82dca62d0826b41a359a
    steps:
      - name: checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: calculate baseline commit
        id: baseline
        run: |
          echo "sha=$(git merge-base HEAD ${{ github.event.pull_request.base.sha }})" >> "$GITHUB_OUTPUT"

      - name: run semgrep differential analysis
        run: |
          semgrep scan \
            --config .semgrep \
            --baseline-commit "${{ steps.baseline.outputs.sha }}" \
            --sarif \
            --output SourceCodeAnalysisDiff.sarif \
            --error \
            .

      - name: upload source code differential report
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: source-code-analysis-diff
          path: SourceCodeAnalysisDiff.sarif
          if-no-files-found: error
          retention-days: 5
